using AutoMapper;
using SwiftPay.DTOs.RemittanceDTO;
using SwiftPay.Domain.Remittance.Entities;

namespace SwiftPay.Mapper
{
    public class ConfigurationMapperProfile : Profile
    {
        public ConfigurationMapperProfile()
        {
            // Map CreateRemittanceDto -> RemittanceRequest
            CreateMap<CreateRemittanceDto, RemittanceRequest>()
                // RemitId is generated by the database / configuration, do not map from DTO
                .ForMember(dest => dest.RemitId, opt => opt.Ignore())
                // Audit fields controlled by server
                .ForMember(dest => dest.CreatedDate, opt => opt.Ignore())
                .ForMember(dest => dest.UpdateDate, opt => opt.Ignore())
                .ForMember(dest => dest.IsDeleted, opt => opt.Ignore());

            //// Optional: map back from entity to DTO for responses if needed
            //CreateMap<RemittanceRequest, CreateRemittanceDto>()
            //    .ForMember(dest => dest.CustomerId, opt => opt.MapFrom(src => src.CustomerId))
            //    .ForMember(dest => dest.BeneficiaryId, opt => opt.MapFrom(src => src.BeneficiaryId))
            //    .ForMember(dest => dest.FromCurrency, opt => opt.MapFrom(src => src.FromCurrency))
            //    .ForMember(dest => dest.ToCurrency, opt => opt.MapFrom(src => src.ToCurrency))
            //    .ForMember(dest => dest.SendAmount, opt => opt.MapFrom(src => src.SendAmount));
        }
    }
}
